### PR TITLE
Add flake

### PR DESCRIPTION
**Pull request by GTrunSec**

### CODE REVIEW

**Comment by gilligan** [comment]
Currently there is neither need for nor any benefit in adding a flake so i'll close this.

**Comment by mkaito** [comment]
Hello, please forgive me for being so forward, but would you mind expanding on why you don't think a flake would be useful?

**Comment by andir** [comment]
You can just add this repo with `flake = false` and add that to your overlays in the consuming project.

**Comment by GTrunSec** [comment]
>You can just add this repo with flake = false

Sure, I did it. Thanks.
https://github.com/GTrunSec/CyberChef-nix-flake/blob/81d6133baa6c1ba091ace6613cba441aeeb4d830/flake.nix#L11

**Comment by ilkecan** [comment]
Why do you think there is no benefit in being able to just write this
```
overlays = [
  npmlock2nix.overlay
];
```
as opposed to having to write this
```
overlays = [
  (final: prev: { npmlock2nix = import npmlock2nix { pkgs = prev; }; })
];
```
every time?

**Comment by mikepurvis** [comment]
Another 👍 here for first-class Flake support, please!

**Comment by andir** [comment]
I promise that once the Flakes RFC is accepted and it isn't experimental anymore that it will happen. Until then: I don't want to fight breakage.

**Comment by winston0410** [comment]
Again I am looking for flake support as well.

**Comment by doronbehar** [comment]
Perhaps now that Nix 2.5 is released can we consider Flakes as stable enough? :pray:

**Comment by andir** [comment]
I'll not add flakes to the repo as the CLI still is still changing every now and then. I try to support what we have in this repo as good as I can. Adding flakes adds yet another code path that we have to test and support. Also adds yet another pinning of nixpkgs.

Whenever I try flakes locally it seems like a good idea but it simply isn't mature enough. Once it is stabelized with the proper RFC process it'll be supported.

**Pull request closed without merging**
