### PR TITLE
overwrite node_modules symlink when appropriate

### LINKED ISSUE #50: repeated invocation complains about node_modules symlink that it created
**Describe the bug**

I'm using npmlock2nix with the default `node_modules_mode`: `symlink`. I'm using the `shell` attribute in my `shell.nix`. I'm also using direnv. When I cd to my project, if there is no `node_modules` present, it gets created a symlink to the nix store. If I `cd .` or cd somewhere else and back, I get `[npmlock2nix] There is already a node_modules directory. Not replacing it.` and my shell is broken.

**To Reproduce**

Use the default symlink mode, the shell, and direnv, and cd to the project twice.

**Expected behavior**

I expect the symlink to be maintained with no error.

**Environment**
 - OS name + version: NixOS 20.09
 - Version of the code: commit 7a321e2477

### PR DESCRIPTION
**Pull request by dnr**
Fixes #50

I didn't look at tests yet. Let me know if this is the right direction and I can work on some tests.

### CODE REVIEW

**Comment by andir** [comment]
Seems to be the same (to some degree) as #56

**Comment by dnr** [comment]
Yes, pretty much. Mine puts the code in `add_node_modules_to_cwd` and does a couple more checks, but same idea.

**Comment by andir** [comment]
@dnr mind having another look at #56. Does that also address all your requirements?

**Comment by dnr** [comment]
Yup, that should do it.

It wasn't entirely clear if the `passthru` bits in that pr were intended to address #51 somehow? Anyway, that conversation can continue in another issue/pr.

**Pull request closed without merging**
